fix: #1266 update create_user and update_user length in db
bcgov/nr-forests-access-management pull request #1275
Opened 2024-03-27 23:11 UTC by MCatherine1994

refs: #1266

`fam_app_environment`, `fam_role_type` and `fam_user_type_code` has no create_user and update_user column
`fam_application_admin` no need to change, cause no bceid can grant application admin

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/f13160a3-6e8d-48d1-9466-db4a98a2a11a)

2024-03-27 23:12 UTC, MCatherine1994 commented
I wonder for the `fam_application_admin` table, there is no need to change the create/update user length, cause no bceid can grant application admin. But do we need to keep consistency for the length and update to 100 chars as well?

2024-03-28 15:58 UTC, basilv commented
I agree there's no need to change FAM_APPLICATION, but its easier for consintency to have all these audit columns the same length, so lets ensure that audit columns in all tables are updated.

2024-03-28 16:00 UTC, basilv commented on server/flyway/sql/V45__create_and_update_user_length_increase.sql
> +ALTER TABLE app_fam.fam_application_client
Missing alter table for fam_application_admin (model was changed).

2024-03-28 16:01 UTC, basilv requested changes
add fam_application_admin and any other tables with audit columns to sql script

2024-04-02 17:35 UTC, basilv approved these changes

2024-04-02 20:35 UTC, merged