feat: #1626 Get user role assignment endpoint backend pagination
bcgov/nr-forests-access-management pull request #1634
Opened 2024-10-22 21:18 UTC by ianliuwk1019

WIP...

2024-10-22 21:56 UTC, ianliuwk1019 commented on server/backend/api/app/constants.py
> +MAX_PAGE_SIZE = 100000
This is temporary for 100000/per page since frontend isn't ready for backend pagination, so frontend can still get all records for now.

2024-10-22 23:56 UTC, ianliuwk1019 commented on server/backend/api/app/schemas/pagination.py
> +And, in this case, the validation error default from Pydantic will not be 400, it will be 422 (from Pydantic)
Note, currently built in validation errors from Pydantic is 422. Hope that's acceptable for frontend.

2024-10-25 21:17 UTC, craigyu requested changes
Impressive work! The endpoint works as intended.

However, could you provide the available options on the swagger doc for the sortBy and sortOrder? 
Something like this
![image](https://github.com/user-attachments/assets/149aca35-be77-4c1a-90f5-1cbd5b649c3f)

It's easier for devs when they need to use this endpoint. I know sortBy is very trivial but it's easier without having to guess whether it's `desc` or `dsc` or something else

2024-10-25 21:23 UTC, ianliuwk1019 commented
> Impressive work! The endpoint works as intended.
> 
> However, could you provide the available options on the swagger doc for the sortBy and sortOrder? Something like this ![image](https://private-user-images.githubusercontent.com/25162561/380327308-149aca35-be77-4c1a-90f5-1cbd5b649c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4OTE0NzEsIm5iZiI6MTcyOTg5MTE3MSwicGF0aCI6Ii8yNTE2MjU2MS8zODAzMjczMDgtMTQ5YWNhMzUtYmU3Ny00YzFhLTkwZjUtMWNiZDViNjQ5YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDIxMTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZDJkMmQzYzY2ZDUxMjc5N2IwNDU1NmVkMTMzY2YxOTlmNzU3YWRjNDU1MGI0MzBmZmFhNjkxMjc1NmM4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ng1NByD0820rEdK83UEXKVsi7cYIAnWKNLxCOm1z6kQ)
> 
> It's easier for devs when they need to use this endpoint. I know sortBy is very trivial but it's easier without having to guess whether it's `desc` or `dsc` or something else

Ah, good point! I will let you know if I can add them easily.

2024-10-25 22:26 UTC, ianliuwk1019 commented
> 9a87f9d



> Impressive work! The endpoint works as intended.
> 
> However, could you provide the available options on the swagger doc for the sortBy and sortOrder? Something like this ![image](https://private-user-images.githubusercontent.com/25162561/380327308-149aca35-be77-4c1a-90f5-1cbd5b649c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4OTUyNTgsIm5iZiI6MTcyOTg5NDk1OCwicGF0aCI6Ii8yNTE2MjU2MS8zODAzMjczMDgtMTQ5YWNhMzUtYmU3Ny00YzFhLTkwZjUtMWNiZDViNjQ5YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDIyMjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MzhkMTM5MDA2YWM4OThmYmYxNjM4NzM2YTk5YmJkYTcwNTgyNDM1M2IwNTljNmQ4MzM1NmM3MWY0Nzk0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aP2Kk4e0ySMDPZFh8P74y59Jg5cAmYHu-Ry4G3mFYyc)
> 
> It's easier for devs when they need to use this endpoint. I know sortBy is very trivial but it's easier without having to guess whether it's `desc` or `dsc` or something else

I can't find an easy way from FastAPI to add additional information in a nice way. I managed to do that at "description" field using <br> instead:
![image](https://github.com/user-attachments/assets/15c8355a-7d8a-4081-bb57-5b5216f37440)
See if you think this is good.

2024-10-28 17:32 UTC, craigyu approved these changes
thanks for adding them!

2024-10-28 18:08 UTC, merged